module.exports = {
  queues: {
    AUTOMATIC_BREAK_VIDEO_REQUEST_QUEUE: "AUTOMATIC_BREAK_VIDEO_REQUEST_QUEUE",
    AUTOMATIC_BREAK_VIDEO_REQUEST_FINISH_QUEUE: "AUTOMATIC_BREAK_VIDEO_REQUEST_FINISH_QUEUE",
  },
};
